kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: <namespace>
  name: custom-role
rules:
- apiGroups: [""]
  resources: ["namespaces", "secrets", "configmaps"]
  verbs: ["list", "create", "get"]
